version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: user
      POSTGRES_DB: orders
    volumes:
      - orders:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  orders:
